### ISSUE TITLE
Insufficient system resources: read from process failed on Xsede Comet 

### ISSUE THREAD

**Issue by AymenFJA** [iceberg-project/ASIFT#1]
Hello All,
I was trying  to submit a job to Comet with Entk  and i got this error .

```
2018-06-13 22:48:59,344: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : Pilot has failed
2018-06-13 22:48:59,385: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : ERROR   : Resource request submission failed
2018-06-13 22:48:59,385: radical.entk.appmanager.0000: MainProcess                     : MainThread     : ERROR   : Error in AppManager
Traceback (most recent call last):
  File "/home/aymen/.local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 252, in run
    self._resource_manager._submit_resource_request()
  File "/home/aymen/.local/lib/python2.7/site-packages/radical/entk/execman/resource_manager.py", line 319, in _submit_resource_request
    raise Exception
Exception

2018-06-13 22:48:59,385: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating WFprocessor
2018-06-13 22:48:59,385: radical.entk.wfprocessor.0000: MainProcess                     : MainThread     : ERROR   : Could not terminate wfprocessor process
Traceback (most recent call last):
  File "aymen_script_comet.py", line 61, in <module>
    appman.run()
  File "/home/aymen/.local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 443, in run
    self._wfp.end_processor()
  File "/home/aymen/.local/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 601, in end_processor
    self._logger.debug('Attempting to end WFprocessor... event: %s' % self._wfp_terminate.is_set())
AttributeError: 'WFprocessor' object has no attribute '_wfp_terminate'
aymen@js-157-181:~/SummerRadical/radical.entk/examples/user_guide/ASIFT/demo_ASIFT_src/build$ 2018-06-13 22:49:11,441: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-1       : ERROR   : Exception in job monitoring thread: Insufficient system resources: Insufficient system resources: read from process failed '[Errno 5] Input/output error' : (RUNNING:
20276.0:DONE:0
24109.0:RUNNING:
24109.0:DONE:0
29020.0:RUNNING:
29020.0:DONE:0
15374.0:RUNNING:
15374.0:DONE:0
3263.0:RUNNING:
3263.0:DONE:0
20801.0:RUNNING:
20801.0:DONE:0
Shared connection to comet.sdsc.xsede.org closed.
) (()) (/home/aymen/.local/lib/python2.7/site-packages/saga/utils/pty_exceptions.py +64 (translate_exception)  :  e = se.NoSuccess ("Insufficient system resources: %s" % cmsg))
2018-06-13 22:49:11,442: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-1       : ERROR   : Cancel job monitoring for ssh://comet.sdsc.xsede.org/

```

**Comment by shantenujha** [comment]
Aymen: You’re likely to have better / quicker response by linking this ticket to RADICAL-EnTK issue tracker. Not sure RADICAL-EnTK / Cybertools team monitor these threads.

**Comment by AymenFJA** [comment]
I will close it and open a new ticket in the RADICAL-EnTK.

thanks.

**Comment by shantenujha** [comment]
I wasn’t necessarily implying that you close the ticket, but to open an issue in RADICAL-EnTK and cross link to here.
